/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for IntArrayNBT AST Node type
* by the ASTNode.java.ftl template
*/
package org.allaymc.snbt.ast;

public class IntArrayNBT extends BaseNode {
}


