/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for ListNBT AST Node type
* by the ASTNode.java.ftl template
*/
package org.allaymc.snbt.ast;

public class ListNBT extends BaseNode {
}


