/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Literal Token subclass
* by the ASTToken.java.ftl template
*/
package org.allaymc.snbt.ast;

import org.allaymc.snbt.SNBTLexer;
import org.allaymc.snbt.Token;


public class Literal extends Token {

    public Literal(TokenType type, SNBTLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


