/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for ByteArrayNBT AST Node type
* by the ASTNode.java.ftl template
*/
package cn.allay.snbt.ast;

public class ByteArrayNBT extends BaseNode {
}


