/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for KeyValuePair AST Node type
* by the ASTNode.java.ftl template
*/
package cn.allay.snbt.ast;

public class KeyValuePair extends BaseNode {
}


