/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for LongArrayNBT AST Node type
* by the ASTNode.java.ftl template
*/
package cn.allay.snbt.ast;

public class LongArrayNBT extends BaseNode {
}


