/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Value AST Node type
* by the ASTNode.java.ftl template
*/
package cn.allay.snbt.ast;

public class Value extends BaseNode {
}


