/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for WHITESPACE Token subclass
* by the ASTToken.java.ftl template
*/
package cn.allay.snbt.ast;

import cn.allay.snbt.SNBTLexer;
import cn.allay.snbt.Token;


public class WHITESPACE extends Token {

    public WHITESPACE(TokenType type, SNBTLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


